# Generated by Django 3.2.23 on 2024-01-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('user_name', models.CharField(default=None, max_length=25)),
                ('password', models.CharField(default=None, max_length=10)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
